<a href="https://colab.research.google.com/github/yiyu-chen-labs/llm-from-scratch/blob/main/00_pytorch_fundementals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

print("hello i am exicted to learn pytorch!")

In [ ]:
!nvidia-smi

Sat May 30 04:38:02 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   43C    P8             13W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
## 00.PyToech Fundementals


In [ ]:
import torch

In [ ]:
print(torch.__version__)

2.11.0+cu128


In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

### Random Tensors
Why random tensors?

Random tensors are important cu zthe way many neural netowkrs learn is that thye start with tensors full of random numbers and them afjust those random numbers to better represent the data


`Start with Random tensors -> look at data -> update random numbers -> look at data -> update randome numberse`

In [ ]:
#create a random tensors of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8861, 0.7418, 0.3994, 0.7738],
        [0.3594, 0.7801, 0.0117, 0.2320],
        [0.5112, 0.8764, 0.0795, 0.7303]])

In [ ]:
random_tensor.ndim

2

###Zeroes and ones

In [ ]:
#Create a tensor of all zeros

In [ ]:
zeros = torch.zeros (size = (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones (size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
#use torch.arange()
one_to_ten = torch.arange(start = 1, end =11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#creating tensos like
ten_zeros= torch.zeros_like (input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###Tensor Datatypes
**Notes:** Tensor datatypes is one of the 3 big error you will run into with pytorch & deel learning

1.  Tensors not right datatype - use `tensor.dtype`
2.  Tensors not right shape - use `tensor.shape`
3.  Tensors not on the rigth device - use `tensor.device`




In [ ]:
#create a tensor
some_tensor= torch.rand(3,4)
some_tensor

tensor([[0.4490, 0.6403, 0.6239, 0.4571],
        [0.6826, 0.8075, 0.6167, 0.6925],
        [0.0148, 0.4273, 0.5164, 0.8152]])

In [ ]:
#Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.4490, 0.6403, 0.6239, 0.4571],
        [0.6826, 0.8075, 0.6167, 0.6925],
        [0.0148, 0.4273, 0.5164, 0.8152]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


###Manipulating Tensors(tensor operations)

Tensor operations include:
* Addition
* Substraction
* Mulptiplication(element-wise)
* Division
* Matrix Multiplication


In [ ]:
#Create a tneost and add 10 to it
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [ ]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor -10

tensor([-9, -8, -7])

In [ ]:
tensor

tensor([1, 2, 3])

### Matric Multiplication

Two main ways of perfomring multipliucation is neural networks and deep learning:


1.   Element-wise multiplication
2.   Matrix multiplication (dot-product)



In [ ]:
#Elemetn wise multiplication
print(tensor, "*", tensor)
print(f"Equals:{tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [ ]:
#Matrix Multiplication
%%time
torch.matmul(tensor, tensor)

CPU times: user 0 ns, sys: 302 µs, total: 302 µs
Wall time: 261 µs


tensor(14)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 849 µs, sys: 0 ns, total: 849 µs
Wall time: 759 µs


### One of the most common errors in deep learning:shape error

link here:http://matrixmultiplication.xyz/


In [ ]:
# shape for matric multiplication
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])


In [ ]:
torch.mm(tensor_A, tensor_B.T) #torch.mmi shte smae as torch.matmal


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
#find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
#find the max
torch.max(x),x.max()

(tensor(90), tensor(90))

In [ ]:
#find the mean - note: the torch.mean() function requires a tensor of float32 datatype towork
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
#fund the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max


In [ ]:
x.argmin()


tensor(0)

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x[3]

tensor(30)

In [ ]:
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping - rehsaprs an input tensor to a define shape
* View - return  a viewof an input tensor of certain shape but keep the same memeory as the original tensor
* Stacking - combine multiple tensors on top of each other(vstack) or side by side
* Squeeze - removes all `1` dimensinos from a tensor         
* Unsqueeze - add a `1` dimensinos to a target tensor
* Permute - Return a view of the input with dimension permuted(swapper) in a certain way





## 1.Reshaping (重塑) —— 「黏土變變變」
ELI5：就像一塊黏土，你可以把它搓成長條型，也可以把它壓成方塊型，但黏土的總量是不變的。
幹嘛用：當你需要把一長條數字（例如 6 個數）變成一個表格（例如 2x3）時。

In [ ]:
import torch
x = torch.arange(6)
x, x.shape

(tensor([0, 1, 2, 3, 4, 5]), torch.Size([6]))

In [ ]:
x_reshaped = x.reshape(2,3)
x_reshaped, x_reshaped.shape

(tensor([[0, 1, 2],
         [3, 4, 5]]),
 torch.Size([2, 3]))

In [ ]:
# create a tensor
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
#add an extra dimension
x_reshaped = x.reshape (1,9)
x_reshaped, x_reshaped.shape


(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

## 2. View (視圖) —— 「換個角度看積木」
ELI5：想像你有一排士兵。你從前面看是「一橫排 6 個人」，從側面看可能是「兩排，每排 3 個人」。士兵沒動，只是你看的角度變了。
注意：它跟 Reshape 很像，但它共享記憶體。如果你改了原本的士兵（改了數值），View 出來的結果也會跟著變！
範例：用法跟 reshape 幾乎一樣 x.view(2, 3)。

In [ ]:
#chagne the view
z = x.view(1,9)
z, z.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# changing z changes x (because a view of a tensor shares the same memory as the original)
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

## 3. Stacking (堆疊) —— 「樂高大組合」
ELI5：這就是把好幾塊一樣的積木黏在一起。
VStack：上下疊（變高）。
HStack：左右連（變寬）。
幹嘛用：把多張照片、多個數據組合成一個大的資料包。

In [ ]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

stacked = torch.stack([x, y], dim=0) # 預設 stack 會增加一個新維度
stacked
# 變成：
# [[1, 2, 3],
#  [4, 5, 6]]

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# y = torch.arange(11.,20.)
x_stacked = torch.stack([x,x,x,x], dim = 0)
x_stacked


tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

##4. Squeeze (擠壓) —— 「把空箱子壓扁」
ELI5：想像你買了一個大紙箱，結果裡面只放了一個小盒子。那個大紙箱就是「多餘的維度 (1)」。Squeeze 就是把這些只有 1 層的空殼子通通拿掉，讓資料變緊湊。
幹嘛用：有時候電腦會給你 [[[ 1, 2, 3 ]]] 這種很煩的結構，你只需要 [1, 2, 3]。

In [ ]:
x = torch.zeros(1, 1, 5) # 形狀是 (1, 1, 5)
squeezed = x.squeeze()     # 形狀變成 (5)
squeezed

tensor([0., 0., 0., 0., 0.])

In [ ]:
# torch.squeeze() =  rmove all single dimensino from a taget tenros
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

#remove extra dimesnio from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")


Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


## 5. Unsqueeze (增加維度) —— 「幫禮物加個包裝盒」
ELI5：跟 Squeeze 相反。你現在有一個玩具，你想把它裝進一個盒子裡，這樣它就多了一層「包裝」。雖然內容沒變，但現在它是有「層次」的。
幹嘛用：AI 模型通常規定要「一疊照片」才能輸入。如果你只有「一張照片」，你就得幫它 unsqueeze 一下，假裝它是「一疊只有一張的照片」。


In [ ]:
import torch
x = torch.tensor([1, 2, 3])

print(x.size())           # 輸出: torch.Size([3])
unsqueezed = x.unsqueeze(dim=0)
print(unsqueezed.size())  # 輸出: torch.Size([1, 3])

torch.Size([3])
torch.Size([1, 3])


In [ ]:
ㄇㄣ#torch.unsqueeze() - add a single dimension to a target tensor at a specific dim
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

#torch,permute - rearragnethe dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) #[height, width, color_channels]

#permute the original tensor to rearrage the axis(or dim) order
x_permuted = x_original.permute(2,0,1) #shifts axis 0->1, 1->2, 2->0

print("")
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") #[color_channels, height, width]



New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
x_reshaped.shape

torch.Size([1, 9])

In [ ]:
x_reshaped.squeeze()


tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
print(x_original.shape)
print(x_original[0].shape)
print(x_original[0, :, :].shape)


torch.Size([224, 224, 3])
torch.Size([224, 3])
torch.Size([224, 3])


In [ ]:
### Indexing (selecting data from tensors)
#indexing with Pytorch is similar to indexing with Numpy

In [ ]:
#create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

## 6. Permute (換位/置換) —— 「轉動方塊」
ELI5：想像你拿著一個魔術方塊，本來是看「正面、上面、側面」。Permute 讓你把「側面變成正面，正面變成上面」。它會重新排列維度的順序。
幹嘛用：這是處理圖片最常用的招數！
電腦讀圖通常是：(顏色, 高, 寬) -> (C, H, W)
但有些螢幕顯示要：(高, 寬, 顏色) -> (H, W, C)
這時候就要用 permute 來大搬家。

In [ ]:
# 假設有一張圖：(顏色:3, 高:224, 寬:224)
picture = torch.randn(3, 224, 224)

# 我想把「顏色」換到最後面：
permuted = picture.permute(1, 2, 0) # 把原來的第 1, 2 維放到前面，第 0 維放到最後
# 現在形狀變成：(224, 224, 3)

### Indexing (Selecting data form Tensors)
Indexing with Pytorch is similar to indexing with Numpy


In [ ]:
#create a tensor
import torch
x = torch.arange(1,10)
x.reshape(1,3,3)


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
#1. 一維張量 (1D Tensor)：像是在排隊
import torch
x = torch.tensor([10, 20, 30, 40])

print(x[0]) # 拿第 0 個（第一個）：10
print(x[3]) # 拿第 3 個（第四個）：40

tensor(10)
tensor(40)


In [ ]:
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# 拿第 0 排的第 1 個數字
print(x[0, 1]) # 結果是 2

# 拿最後一排的最後一個
print(x[2, 2]) # 結果是 9
# 拿第一排的"所有!"
print(x[:,0])
# 拿第一列的"所有!"
print(x[0,:])

tensor(2)
tensor(9)
tensor([1, 4, 7])
tensor([1, 2, 3])


In [ ]:
# 建立一個 3x3x3 的全 0 張量，然後改一點數字
x = torch.zeros(3, 3, 3)
print(x)
x[0, 0, 0] = 99 # 第一本書的第一排第一個變成 99

print(x[0, 0, 0]) # 結果：99

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])
tensor(99.)


In [ ]:
x = torch.tensor([1, 2, 3, 4, 5])
print(x[-1]) # 最後一個：5
print(x[-2]) # 倒數第二個：4

tensor(5)
tensor(4)


In [ ]:
x = torch.tensor([0, 1, 2, 3, 4, 5])
print(x[1:4]) # 拿第 1 號到第 3 號 (不含 4)
# 結果：tensor([1, 2, 3])

tensor([1, 2, 3])


In [ ]:
#6. Slicing (切片) —— 「拿一小段」如果你不想要全部，只想要其中一段，可以用 開始:結束 (但不包含結束的那一個喔！)。
x = torch.tensor([0, 1, 2, 3, 4, 5])
print(x[1:4]) # 拿第 1 號到第 3 號 (不含 4)

tensor([1, 2, 3])


##PyTorch tensors & NumPy
NumPy is a popular scientific Python numerical libary.



*   Data in Numpy, want in Pytorch tensor -> `torch.form_numpy(ndaarray)`
* PyTorch tensor ->Numpy ->`torch.Tensor.numpy()`



In [ ]:
#numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)#when converting from numpy-> pytorch (default:float64)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
tensor.dtype

torch.float64

In [ ]:
#change the value of array, what will this do to tensor?
array = array +1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
#Tensor to Numpy Array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()

tensor=tensor +1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
import torch
#create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)

tensor([[0.5008, 0.0159, 0.6833, 0.8457],
        [0.5217, 0.8889, 0.7122, 0.7045],
        [0.6121, 0.7758, 0.0011, 0.0562]])
tensor([[0.2376, 0.3626, 0.5710, 0.5510],
        [0.2922, 0.9158, 0.0743, 0.0367],
        [0.2136, 0.4914, 0.9325, 0.8339]])


In [ ]:
#Let's make some random but reproducible tensors
import torch

#set the random seet
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running Tensor and PyTorch objects on the GPUs (and making faster computations)

GPUs =  faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything good
